---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# clustr

<!-- badges: start -->
<!-- badges: end -->

A set of data clustering tools that increases data mining efficiency.

## Installation

You can install the released version of clustr from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("clustr")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Stevo795/clustr")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(clustr)
## basic example code
# Input the "label" column as y and the rest of the dataframe as x; 
#  centers: number of clusters
#  nstart: number of random sets to be selected 
data=mtcars
clusters_result = kmeans_hist(y=data$cyl, 
                              x=subset(data, select=- cyl),
                              centers=3,
                              nstart=5)
```

This function returns the result of the clustering
```{r}
clusters_result
```


